### PR TITLE
Recursive def super method fix

### PR DESCRIPTION
**Pull request by sharad**
Need to revert previous fix, 
I was not able properly understand the issue

So reverted previous fix and added correct fix for it.

Thanks.

### CODE REVIEW

**Comment by skeeto** [comment]
Sharad, would you be interested in taking ownership of @? I haven't 
touched or thought about it in over 5 years, and I don't expect that to 
ever change.

**Comment by sharad** [comment]
Hi Wellons

Thanks for the invitation.

I am using @/at-el lib for
https://github.com/sharad/elpa-pkgs/tree/master/lotus/activity

I can take ownership of @/at-el
even though I may not be very good with lower level programming
as evident from the 2018 last change.


Thanks and Regards
--
/sharad

**Comment by skeeto** [comment]
Now that you're a collaborator I think you can push and merge and such, so 
you can manage the repository without my input. I can formally transfer 
ownership, too, if you like, though you'd need to update the MELPA entry 
to the new URL. If you choose that route, I can chime in on the MELPA PR 
to "ok" it.

Thanks for doing this!

**Comment by sharad** [comment]
Please sure update MELPA to new url

--
/sharad

**Pull request merged**
